### ISSUE TITLE
Is it possible to build Audioneex on CentOS 7 x86_64 with default build tools?

### ISSUE THREAD

**Issue by kvishnivetsky** [a-gram/audioneex#1]
Hi,

I'm on CentOS 7 x86_64 with CMake v2.8.12.2 and GCC v5.3.1 20160406 (Red Hat 5.3.1-6)

Is it possible to build this software with this tools or I need install more recent versions from third party repos?

**Comment by a-gram** [comment]
Hi,

the software requires CMake v3.5 as a minimum and GCC 6/7. Probably GCC 5 will compile it as well (used to with older versions) but your build system is quite old so you have to upgrade it.

Cheers
