### ISSUE TITLE
Installation broken after the latest commit

### ISSUE THREAD

**Issue by JohannesTK** [a-gram/audioneex#2]
Running:

```
cmake -DWITH_EXAMPLES=ON -DWITH_ID3=ON
make
```

Ends up with:

`ERROR: [install_linux] Could not find the NDK. Please set either the ANDROID_NDK_HOME or ANDROID_NDK_ROOT environment variable with the path to your NDK installation directory.`

Works well before the last commit:

`git checkout 83de59d03d47a6858420d886ca73e87cab0de47d`

There is no need for building Android. The previous doc showed it as optional. Is it a hard requirement now?

**Comment by a-gram** [comment]
Yeah it's a bug. I'll fix it at the next commit. Meanwhile you can remove line 164 in the install_linux script if Android build is not needed. Let me know if that solves the issue.
