### ISSUE TITLE
how to run examples ?

### ISSUE THREAD

**Issue by cafefars** [a-gram/audioneex#3]
hi
I built the source code with Ubuntu OS
But I can't run example 1,example 2,example 3 with  gcc
~/audioneex/_build/linux-x64-gnu740/release$ gcc example1 '1.mp3'

example1: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
please help me out
Thanks

**Comment by a-gram** [comment]
I think the following may help:

[Introduction to Linux](https://linux.die.net/Intro-Linux/)
[Bash Guide for Beginners](https://linux.die.net/Bash-Beginners-Guide/)
[Using the GNU Compiler Collection (GCC)](https://gcc.gnu.org/onlinedocs/gcc-7.5.0/gcc/)
