### ISSUE TITLE
An example that doesn't work with the Couchbase Database

### ISSUE THREAD

**Issue by cafefars** [a-gram/audioneex#4]
Hi
I build audioneex in Ubuntu with option DATASTORE_T =CBDataStore WITH_EXAMPLES = ON and I configured Couchbase value in example1.cpp (ip, user, password and port)
But when I run Example 1 with the -u parameter  (./example1 -u 127.0.0.1 /mp3) this error is show : ERROR: file not found 127.0.0.1/data.idx
It also works correctly with TokyoCabinet.
Please help me

**Comment by hpuriamanesh** [comment]
Yes
I think it doesn't build with the couchbase database
